### ISSUE TITLE
请问kotlin版本是多少呢？我想写的更简洁点

### ISSUE THREAD

**Issue by ilovexy2tom** [TaylorKunZhang/single-click#2]
请问kotlin版本是多少呢？我想写的更简洁点

我现在只能写成这样

onSingleClick(1000, true, View.OnClickListener {

如果是onSingleClick{
}
就会报错

我的是1.3.72

**Comment by TaylorKunZhang** [comment]
这个项目里面用的版本是 1.4.31，1.3.72 确实不行，把版本改到 1.4.0 或者更新版本就可以了
